package au.edu.unsw.soacourse.topdown;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-03-08T17:49:37.519+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://topdown.soacourse.unsw.edu.au", name = "TopDownSimpleService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TopDownSimpleService {

    @WebMethod(action = "http://topdown.soacourse.unsw.edu.au/downloadFile")
    @WebResult(name = "downloadFileResponse", targetNamespace = "http://topdown.soacourse.unsw.edu.au", partName = "parameters")
    public DownloadFileResponse downloadFile(
        @WebParam(partName = "parameters", name = "downloadFileRequest", targetNamespace = "http://topdown.soacourse.unsw.edu.au")
        DownloadFileRequest parameters
    );

    @WebMethod(action = "http://topdown.soacourse.unsw.edu.au/importMarketData")
    @WebResult(name = "importMarketDataResponse", targetNamespace = "http://topdown.soacourse.unsw.edu.au", partName = "parameters")
    public ImportMarketDataResponse importMarketData(
        @WebParam(partName = "parameters", name = "importMarketDataRequest", targetNamespace = "http://topdown.soacourse.unsw.edu.au")
        ImportMarketDataRequest parameters
    );
}
